FROM python:3.11-slim
WORKDIR /app/frontend
RUN pip install --no-cache-dir streamlit requests
COPY frontend/ .
EXPOSE 8501
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
